apiVersion: v1
kind: Service
metadata:
  name: recordingbot
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: recordingbot
