apiVersion: apps/v1
kind: Deployment
metadata:
  name: recordingbot
  labels:
    {{- include "recordingbot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replica }}
  selector:
    matchLabels:
      app: recordingbot
  template:
    metadata:
      labels:
        app: recordingbot
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.app.image }}:{{ .Values.app.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            {{- toYaml .Values.app.env | nindent 12 }}

          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8081
              protocol: TCP

          livenessProbe:
            httpGet:
              path: /status
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /status
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10