apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
spec:
  type: ClusterIP
  ports:
    - name: elasticsearch
      port: 9200
      targetPort: 9200
  selector:
    app: data-elasticsearch
