apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-elasticsearch
  labels:
    {{- include "recodingbot.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-elasticsearch
  template:
    metadata:
      labels:
        app: data-elasticsearch
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
          imagePullPolicy: IfNotPresent
          env:
            - name: ES_JAVA_OPTS
              value: -Xms1g -Xmx1g
            - name: discovery.type
              value: single-node
          ports:
            - containerPort: 9200
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /usr/share/elasticsearch/data/
      nodeSelector:
        {{- toYaml .Values.elasticsearch.nodeSelector | nindent 8 }}
      volumes:
        - name: elasticsearch-data
          hostPath:
            path: {{ .Values.elasticsearch.dataPath }}
          
              

