name: CI

on:
  push:
    branches-ignore:
      - master
      - staging

  pull_request:

jobs:
  docker-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

        # setup docker actions https://github.com/docker/build-push-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          # https://github.com/docker/build-push-action/issues/220
          context: .
          tags: wire/ci-test-image
          push: false